### PR TITLE
Instrument selection + "hard" mode only allows 3 plays

### LINKED ISSUE #33: [FEATURE] Let users change instruments
**Is your feature request related to a problem? Please describe.**
Add a dropdown to the right of the top play button that lets users change their instrument from the default "grand piano" to a saxophone, etc. 

**Describe the solution you'd like**
When a different instrument is selected, the sound plays the new instrument. 

**Estimated feature size**
Medium. implementation steps:
- add dropdown (and research design library + fontawesome icons for each instrument)
- Edit the `playSequence` function to accept an instrument argument

### PR DESCRIPTION
**Pull request by lpatmo**
## Description
This PR resolves #33 

- [x] Support instrument selection
- [x] Remove "tricky" mode and support only 3 plays under "hard" mode 

## Before
image
image

## After

image
image

### CODE REVIEW

**Review by ISPOL — CHANGES_REQUESTED** [review]
Hard mode doesn't mean much if you can switch difficulties to hear the song again, then switch back.

Changing instruments doesn't update the user input playback notes immediately.

**Review by ISPOL — APPROVED** [review]
We can revisit the difficulty issue later, the other things look fine.

**Comment by lpatmo** [comment]
Thanks @ISPOL for pairing with me to figure out the two bugs re: instrument not updating + the instrument not stopping if the play button is clicked multiple times. 

1) For the former, we made sure to add `instrument` to the useCallbacks dependency array.

2) For the latter, we created a `instrumentsObj` object containing each instrument pointing to a different sound font, and created a stopAll function that would stop each sound font. 

```
const instrumentObjs = {};
for (let i = 0; i < instrumentsArr.length; i++) {
    instrumentsObj[instrumentsArr[i]] = new Soundfont(context, { instrument: instrumentsArr[i] });
}
```

```
function stopAll() {
    instrumentsArr.forEach((instrument) => {
        instrumentsObj[instrument].stop();
    })
}```

**Comment by lpatmo** [comment]
For difficulty, I'll create a ticket to support session storage.

**Review by arturolei — APPROVED** [review]
UI still feels clunky but we can fix that later. If you switch from Hard to Normal, the message about having run out of tries still displays.

**Pull request merged**
