### PR TITLE
Responsive layout

### LINKED ISSUE #73: [FEATURE] Responsive layout
**Is your feature request related to a problem? Please describe.**
On large screen widths, move the piano to the right side.

On smaller screens, have the layout be vertical.

### PR DESCRIPTION
**Pull request by lpatmo**
## Description
This PR resolves #73

## Before
Vertical-only layout

## After
image
image

## Implementation Details 
- [x] Used Grid and Paper components

### CODE REVIEW

**Review by arturolei — CHANGES_REQUESTED** [review]
It looks really weird on wide-screen and the actual answer form is too far to one side. If the answer form is supposed to be one of the central points/focus areas, it should be in the center.

image

**Comment by lpatmo** [comment]
@arturolei Changed it to be always vertical. Also made the piano keyboard shorter in height.

**Review by ISPOL — APPROVED** [review]
Looks fine to me.

**Comment by arturolei** [comment]
Looks okay but check console for why there's an error message with `soundfont-player.js`

**Review by arturolei — APPROVED** [review]
Looks better

**Pull request merged**
