### PR TITLE
Song selector UI

### PR DESCRIPTION
**Pull request by lpatmo**
Updates the UI. Feedback welcome.

### CODE REVIEW

**Review by ISPOL — APPROVED** [review]
Looks functional. 

Minor changes: 

I would recommend some sort of label or indicator if we're not using the placeholder text to make it explicit what the number in the navbar is for.

Also possibly disable or grey out the - and + buttons when the value is 1 or the last song.

**Review by ISPOL — CHANGES_REQUESTED** [review]
Major issue:
Navbar is also used in practice mode, and is crashing because it wasn't updated to handle some of the new additions.

Minor issues 

I would recommend some sort of label or indicator if we're not using the placeholder text to make it explicit what the number in the navbar is for.

Also possibly disable or grey out the - and + buttons when the value is 1 or the last song.

**Comment by lpatmo** [comment]
> Navbar is also used in practice mode, and is crashing because it wasn't updated to handle some of the new additions.

Fixed.

> I would recommend some sort of label or indicator if we're not using the placeholder text to make it explicit what the number in the navbar is for.

Added. Named it "Day #". 

> Also possibly disable or grey out the - and + buttons when the value is 1 or the last song.

@ISPOL I could use some help with this... couldn't figure it out based on the code and based on https://mui.com/base-ui/react-number-input/.

**Comment by ISPOL** [comment]
> Fixed.
Is there a way to use default values for the props you pass in so we don't have to remove it from Practice Mode entirely? It'd probably be useful for when we're inputting puzzles.

> Added. Named it "Day #".
Text could be a little bigger, or alternatively we could use the same font as the logo? Otherwise looks fine.

> @ISPOL I could use some help with this... couldn't figure it out based on the code and based on https://mui.com/base-ui/react-number-input/.
Doesn't seem that important if the functionality is working (and it does look like it's working), so we can table it for later if it'd be a lot of work for a minor improvement.

**Comment by ISPOL** [comment]
Made some changes to practice mode and navbar to get it working. 

Let me know if it looks alright @lpatmo @arturolei

**Review by ISPOL — APPROVED** [review]

**Pull request merged**
