### PR TITLE
Support 8 tiles in difficult mode

### PR DESCRIPTION
**Pull request by lpatmo**
Before: 
image

After: 
image

### CODE REVIEW

**Review by ISPOL — CHANGES_REQUESTED** [review]
Using a ternary operator for the ```numberTiles``` state works while we only have two difficulty modes, but for scalability reasons we might want to switch to something that uses key-value pairs. 

So instead of ```useState(difficultyMode === "difficult" ? 8 : 6);``` it'd be something like:
```useState(difficultyModeObject[difficultyMode]);``` where ```difficultyModeObject``` is an object with key-value pairs of ```difficultyLevel```: ```correspondingTileNumber```

Board state is currently kept if the difficulty mode is changed. This allows somebody to listen to the song unlimited times in normal mode, as well as their guess, then switch to difficult mode, which makes the restrictions in difficult mode trivially bypassed. We should probably reset the board if the difficulty mode is changed.

**Comment by lpatmo** [comment]
@ISPOL Thanks for the feedback!

> Using a ternary operator for the numberTiles state works while we only have two difficulty modes, but for scalability reasons we might want to switch to something that uses key-value pairs.

This is done.

> Board state is currently kept if the difficulty mode is changed. This allows somebody to listen to the song unlimited times in normal mode, as well as their guess, then switch to difficult mode, which makes the restrictions in difficult mode trivially bypassed. We should probably reset the board if the difficulty mode is changed.

I've reset the board and stopped the music if the user changes the difficulty mode.

Also pushed up a change to make sure the music silences if someone mutes the volume mid-play, although it doesn't quite work in the opposite direction and will need to figure that out.

**Comment by lpatmo** [comment]
> 8 rows when switching from normal to difficult then back to normal

This is fixed.

> After winning game and switching difficulty mode, board is reset

Now after you have won the game, you cannot change the difficulty mode anymore. 

@ISPOL Thanks for finding those additional two edge cases! This is now fixed.

**Review by ISPOL — CHANGES_REQUESTED** [review]
Bug: Switching difficulty modes and then quickly trying to play a note eats the note input and automatically changes the difficulty mode to difficult.

**Comment by lpatmo** [comment]
@ISPOL Please correct me if I'm wrong... but I think that issue only comes up if you press the "D" key after trying to switch from "difficult" to "normal" mode. This is because if your cursor is still highlighted on the dropdown, the computer thinks you are pressing "D" for "difficult"

**Comment by ISPOL** [comment]
> @ISPOL Please correct me if I'm wrong... but I think that issue only comes up if you press the "D" key after trying to switch from "difficult" to "normal" mode. This is because if your cursor is still highlighted on the dropdown, the computer thinks you are pressing "D" for "difficult"

That would explain it.

**Review by ISPOL — APPROVED** [review]
Looks good to me now.

**Pull request merged**
