### PR TITLE
Support sharps and flats + tiny piano showing current octave

### LINKED ISSUE #48: [FEATURE] Add black keys to piano
**Is your feature request related to a problem? Please describe.**
After https://github.com/lpatmo/musical-wordle/pull/45 is merged, let's add black keys to the piano. Note that the black keys won't be clickable. 

Reference: 
https://codepen.io/zastrow/pen/kxdYdk 

**Describe the solution you'd like**
CSS issue.

**Estimated feature size**
Medium

### PR DESCRIPTION
**Pull request by lpatmo**
## Description
This PR resolves #48 

## Before

No black keys
image

## After
Support for sharps and flats amongst the first six notes. The octave will also change to reflect which octave the next note belongs to. In the future, I want to display a tiny piano to visually show where on the 88 keys someone is.

image

## Implementation Details 

Followed @ISPOL's suggestion to give each note two digits as a default. 

For example, guess: ["C", "A", "D", "B", "G", "A"] becomes

guess: ["C.", "A.", "D.", "B.", "G.", "A."]

This gives us room to add in "#" and "b", so we can now support melodies like:

guess: ["C#", "A.", "D.", "B.", "G#", "A."]

or:

guess: ["C.", "Ab", "Db", "B.", "G.", "A."]

Note: EITHER sharps or flats are supported, and the keyboard will only show flat notes if `hasFlats=true` exists in the answer.

### CODE REVIEW

**Review by arturolei — APPROVED** [review]
Looks good to me. We should probably add documentation about dependencies and logic

**Review by ISPOL — CHANGES_REQUESTED** [review]
Do we have a keyboard shortcut for the new black keys? If we do, we should make it clear what those shortcuts are, since it wouldn't be as immediately apparent as `A` for `A`. One way to do that would be to add subscripts or labels on the keyboard. Or alternatively, via an instruction panel.

If we don't, then they could be something along the lines of  `Shift`+`A` or `Alt`+`A` for flats/sharps. The `handleKeyDown` callback in `Board.jsx` is where current keypresses are handled, so it'd probably be another case in there, or a modification to the `isNote` function.

 Otherwise looks good.

**Comment by lpatmo** [comment]
@ISPOL Good call! I like the idea of `SHIFT-C/D/F/G/A` for sharps.  

For flats, I'm not sure what the `alt-[]` equivalent would be on a mac keyboard 🤔 

I also like the idea of an instruction panel! But we'll have to think about where to put it... e.g. should it open up as a modal when someone clicks on it? Or should it be right below the keyboard and always visible?

Another idea: we could support having the 7 white keys map to the digits 1-7. And sharps/flats could map to shift-[number].

**Comment by lpatmo** [comment]
@ISPOL @arturolei I added support for sharps and flats via keypress (SHIFT-X) in https://github.com/lpatmo/musical-wordle/pull/109/commits/9f117686e2f5f61e71b37a089026a8262d329d21. 

If the song has sharps on it, you can SHIFT-C, SHIFT-D, SHIFT-F, SHIFT-G, and SHIFT-A to get: C#, D#, F#, G#, and A#

If the song has flats on it, you can do SHIFT-D, SHIFT-E, SHIFT-G, SHIFT-A, and SHIFT-B to get: Db, Eb, Gb, Ab, and Bb.

**Review by ISPOL — APPROVED** [review]
Looks good to me.

**Review by arturolei — APPROVED** [review]
Looks good to me. Tested it on Firefox, Edge, and Chrome

**Pull request merged**
