### PR TITLE
[ISSUE-47] Add support for volume slider

### LINKED ISSUE #47: [FEATURE] Volume adjustment
**Is your feature request related to a problem? Please describe.**
We should let users adjust the volume of the sound. 

**Describe the solution you'd like**
- [ ] Add slider next to the "play the notes" button or somewhere under a settings icon (so you know you're setting the volume for the entire page)
- [ ] User can slide it to adjust the volume (read through docs at https://github.com/danigb/soundfont-player to figure out how to set the `gain`)  

**Estimated feature size**
Large

### PR DESCRIPTION
**Pull request by lpatmo**
## Description
This PR resolves #47 

## Before
No volume slider 

## After

image

## Implementation Details 
- [x] Used useContext

### CODE REVIEW

**Comment by ISPOL** [comment]
The volume of notes played doesn't change in real-time.

**Review by ISPOL — CHANGES_REQUESTED** [review]
Instead of passing down the `volume` state directly in the `playSequence` function, you can try passing down a getter function for the state so the sequence always plays the note at the up-to-date volume.

**Review by ISPOL — APPROVED** [review]
Individual notes now play at the correct volume. Volume still doesn't change in the middle of playing a sequence, but we can leave it (and a mute button) for a future fix.

**Review by arturolei — APPROVED** [review]
Looks good to me.

**Pull request merged**
